wandb_version: 1

activation_func:
  value: ReLU
batch_normalization:
  value: 'No'
data_augment:
  value: 'Yes'
dropout:
  value: 'No'
epoch:
  value: 5
filter_org:
  value: half
filter_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
hidden_units:
  value: 256
num_filters:
  value: 32
prob:
  value: 0.2
