wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712409259.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.4
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
activation_func:
  desc: null
  value: GELU
data_augment:
  desc: null
  value: 'No'
dropout:
  desc: null
  value: 'No'
epoch:
  desc: null
  value: 10
hidden_units:
  desc: null
  value: 256
optimizer:
  desc: null
  value: RMSprop
prob:
  desc: null
  value: 0.3
