wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712435132.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.11.5
      5: 0.16.4
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      10:
      - 3
      13: darwin-arm64
activation_func:
  desc: null
  value: ReLU
batch_normalization:
  desc: null
  value: 'Yes'
data_augment:
  desc: null
  value: 'No'
dropout:
  desc: null
  value: 'Yes'
epoch:
  desc: null
  value: 10
filter_org:
  desc: null
  value: same
filter_size:
  desc: null
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
hidden_units:
  desc: null
  value: 128
num_filters:
  desc: null
  value: 32
prob:
  desc: null
  value: 0.3
